In [98]:
import pandas as pd

df=pd.read_csv('/content/100_Unique_QA_Dataset.csv')
df.head()

                                          question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [99]:
# Tokenize
def tokenize(text):
  text=text.lower()

  text=text.replace("'","")
  text=text.replace('?','')

  return text.split()

In [100]:
tokenize('What is the capital of France?')

['what', 'is', 'the', 'capital', 'of', 'france']

In [101]:
vocab={'<UNK>':0}

In [102]:
def build_vocab(row):
  token_question=tokenize(row['question'])
  token_answer=tokenize(row['answer'])

  merged_tokens=token_question+token_answer

  for token in merged_tokens:
    if token not in vocab:
      vocab[token]=len(vocab)

In [103]:
df.apply(build_vocab,axis=1)

0     None
1     None
2     None
3     None
4     None
      ...
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [104]:
len(vocab)

324

In [105]:
# convert words to numerical indices
def text_to_indices(text,vocab):
  indexed_text=[]
  for token in tokenize(text):
    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<UNK>'])
  return indexed_text

In [106]:
text_to_indices("What is Wscube Tech?",vocab)

[1, 2, 0, 0]

In [107]:
import torch
from  torch.utils.data import Dataset,DataLoader

In [108]:
class QADataset(Dataset):
  def __init__(self,df,vocab):
    self.df=df
    self.vocab=vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self,index):
    row=self.df.iloc[index]
    question=text_to_indices(row['question'],self.vocab)
    answer=text_to_indices(row['answer'],self.vocab)

    return torch.tensor(question),torch.tensor(answer)

In [109]:
dataset=QADataset(df,vocab)

In [110]:
dataset[3]

(tensor([ 1,  2,  3, 17, 18, 19, 20, 21, 22]), tensor([23]))

In [111]:
dataloader=DataLoader(dataset,batch_size=1,shuffle=True)

In [112]:
for question,answer in dataloader:
  print(question)
  print(answer)

tensor([[ 10, 140,   3, 141, 270,  93, 271,   5,   3, 272]])
tensor([[273]])
tensor([[ 10,  75, 208]])
tensor([[209]])
tensor([[ 10, 140,   3, 141, 171,   5,   3,  70, 172]])
tensor([[173]])
tensor([[ 1,  2,  3, 69,  5,  3, 70, 71]])
tensor([[72]])
tensor([[  1,   2,   3,   4,   5, 109]])
tensor([[317]])
tensor([[ 42, 174,   2,  62,  39, 175, 176,  12, 177, 178]])
tensor([[179]])
tensor([[10, 11, 12, 13, 14, 15]])
tensor([[16]])
tensor([[10, 75, 76]])
tensor([[77]])
tensor([[ 42, 250, 251, 118, 252, 253]])
tensor([[254]])
tensor([[ 1,  2,  3, 92, 93, 94]])
tensor([[95]])
tensor([[  1,   2,   3,  92, 137,  19,   3,  45]])
tensor([[185]])
tensor([[ 42, 137,   2, 138,  39, 175, 269]])
tensor([[99]])
tensor([[ 42, 125,   2,  62,  63,   3, 126, 127]])
tensor([[128]])
tensor([[  1,   2,   3,   4,   5, 286]])
tensor([[287]])
tensor([[ 10,  75,   3, 296,  19, 297]])
tensor([[298]])
tensor([[ 10,  96,   3, 104, 239]])
tensor([[240]])
tensor([[ 1,  2,  3, 69,  5, 53]])
tensor([[260]])
tensor([[78, 79, 80, 81, 82, 83, 84]])
tensor([[85]])
tensor([[ 78,  79, 129,  81,  19,   3,  21,  22]])
tensor([[36]])
tensor([[ 10,  11, 157, 158, 159]])
tensor([[160]])
tensor([[ 42, 167,   2,   3,  17, 168, 169]])
tensor([[170]])
tensor([[ 42, 263, 264,  14, 265, 266, 158, 267]])
tensor([[268]])
tensor([[  1,   2,   3, 180, 181, 182, 183]])
tensor([[184]])
tensor([[ 78,  79, 150, 151,  14, 152, 153]])
tensor([[154]])
tensor([[10,  2,  3, 66,  5, 67]])
tensor([[68]])
tensor([[  1,   2,   3, 146, 147,  19, 148]])
tensor([[149]])
tensor([[ 1,  2,  3, 24, 25,  5, 26, 19, 27]])
tensor([[28]])
tensor([[ 42,   2,   3, 274, 211, 275]])
tensor([[276]])
tensor([[ 42, 216, 118, 217, 218,  19,  14, 219,  43]])
tensor([[220]])
tensor([[ 42, 101,   2,   3,  17]])
tensor([[102]])
tensor([[ 42,  18,   2,   3, 281,  12,   3, 282]])
tensor([[205]])
tensor([[  1,   2,   3, 234,   5, 235]])
tensor([[131]])
tensor([[10, 29,  3, 30, 31]])
tensor([[32]])
tensor([[ 42,   2,   3, 210, 137, 168, 211, 169]])
tensor([[113]])
tensor([[  1,   2,   3,   4,   5, 206]])
tensor([[207]])
tensor([[ 42, 255,   2, 256,  83, 257, 258]])
tensor([[259]])
tensor([[42, 86, 87, 88, 89, 39, 90]])
tensor([[91]])
tensor([[  1,   2,   3,  37, 133,   5,  26]])
tensor([[134]])
tensor([[ 78,  79, 195,  81,  19,   3, 196, 197, 198]])
tensor([[199]])
tensor([[ 1,  2,  3, 37, 38, 39, 40]])
tensor([[41]])
tensor([[  1,   2,   3, 163, 164, 165,  83,  84]])
tensor([[166]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[ 1,  2,  3, 17, 18, 19, 20, 21, 22]])
tensor([[23]])
tensor([[ 10,  29, 130, 131]])
tensor([[132]])
tensor([[ 1,  2,  3, 50, 51, 19,  3, 45]])
tensor([[52]])
tensor([[ 1,  2,  3,  4,  5, 53]])
tensor([[54]])
tensor([[ 42, 107,   2, 108,  19, 109]])
tensor([[110]])
tensor([[ 10,  11, 189, 158, 190]])
tensor([[191]])
tensor([[  1,   2,   3,   4,   5, 135]])
tensor([[136]])
tensor([[ 42, 137,   2,  62,  39,   3, 322, 323]])
tensor([[6]])
tensor([[ 42, 117, 118,   3, 119,  94, 120]])
tensor([[121]])
tensor([[10, 55,  3, 56,  5, 57]])
tensor([[58]])
tensor([[ 42,  18, 118,   3, 186, 187]])
tensor([[188]])
tensor([[ 42, 290, 291, 118, 292, 158, 293, 294]])
tensor([[295]])
tensor([[  1,   2,   3, 122, 123,  19,   3,  45]])
tensor([[124]])
tensor([[42, 18,  2, 62, 63,  3, 64, 18]])
tensor([[65]])
tensor([[  1,  87, 229, 230, 231, 232]])
tensor([[233]])
tensor([[  1,   2,   3, 103,   5, 104,  19, 105]])
tensor([[106]])
tensor([[42, 43, 44, 45, 46, 47, 48]])
tensor([[49]])
tensor([[ 10, 140,   3, 141, 142,  12, 143,  83,   3, 144]])
tensor([[145]])
tensor([[  1,   2,   3, 221,   5, 222, 223, 224]])
tensor([[225]])
tensor([[ 10,  75, 111]])
tensor([[112]])
tensor([[1, 2, 3, 4, 5, 8]])
tensor([[9]])
tensor([[ 1,  2,  3,  4,  5, 99]])
tensor([[100]])
tensor([[  1,   2,   3, 146,  86,  19, 192, 193]])
tensor([[194]])
tensor([[ 42, 137,   2, 226,  12,   3, 227, 228]])
tensor([[155]])
tensor([[ 78,  79, 261, 151,  14, 262, 153]])
tensor([[36]])
tensor([[ 42, 312,   2, 313,  62,  63,   3, 314, 315]])
tensor([[316]])
tensor([[ 42, 299, 300, 118,  14, 301, 302, 158, 303, 304, 305, 306]])
tensor([[307]])
tensor([[ 42, 137, 118,   3, 247,   5, 248]])
tensor([[249]])
tensor([[  1,   2,   3, 141, 117,  83,   3, 277, 278]])
tensor([[121]])
tensor([[  1,   2,   3,  33,  34,   5, 245]])
tensor([[246]])
tensor([[  1,   2,   3,   4,   5, 279]])
tensor([[280]])
tensor([[ 78,  79, 288,  81,  19,  14, 289]])
tensor([[85]])
tensor([[ 42, 137,   2, 138,  39, 139]])
tensor([[53]])
tensor([[ 1,  2,  3, 59, 25,  5, 26, 19, 60]])
tensor([[61]])
tensor([[  1,   2,   3,   4,   5, 113]])
tensor([[114]])
tensor([[ 42, 200,   2,  14, 201, 202, 203, 204]])
tensor([[205]])
tensor([[ 10,   2,  62,  63,   3, 283,   5, 284]])
tensor([[285]])
tensor([[ 42,  86,  87, 241, 242,  19,  39, 243]])
tensor([[244]])
tensor([[ 42, 318,   2,  62,  63,   3, 319,   5, 320]])
tensor([[321]])
tensor([[  1,   2,   3,  17, 115,  83,  84]])
tensor([[116]])
tensor([[10, 96,  3, 97]])
tensor([[98]])
tensor([[ 10, 308,   3, 309, 310]])
tensor([[311]])
tensor([[ 1,  2,  3,  4,  5, 73]])
tensor([[74]])
tensor([[  1,   2,   3,  69,   5, 155]])
tensor([[156]])
tensor([[  1,   2,   3,   4,   5, 236, 237]])
tensor([[238]])
tensor([[ 1,  2,  3, 33, 34,  5, 35]])
tensor([[36]])
tensor([[  1,   2,   3,  37,  38,  39, 161]])
tensor([[162]])
tensor([[  1,   2,   3, 212,   5,  14, 213, 214]])
tensor([[215]])

In [113]:
import torch.nn as nn

In [114]:
class SimpleRNN(nn.Module):

  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, embedding_dim=50)
    self.rnn = nn.RNN(50, 64, batch_first=True)
    self.fc = nn.Linear(64, vocab_size)

  def forward(self, question):
    embedded_question = self.embedding(question)
    hidden, final = self.rnn(embedded_question)
    output = self.fc(final.squeeze(0))

    return output

In [115]:
x = nn.Embedding(324, embedding_dim=50)
y = nn.RNN(50, 64, batch_first=True)
z = nn.Linear(64, 324)

a = dataset[0][0].reshape(1,6)
print("shape of a:", a.shape)
b = x(a)
print("shape of b:", b.shape)
c, d = y(b)
print("shape of c:", c.shape)
print("shape of d:", d.shape)

e = z(d.squeeze(0))

print("shape of e:", e.shape)

shape of a: torch.Size([1, 6])
shape of b: torch.Size([1, 6, 50])
shape of c: torch.Size([1, 6, 64])
shape of d: torch.Size([1, 1, 64])
shape of e: torch.Size([1, 324])

In [116]:
learning_rate=0.001
epochs=20

In [117]:
model=SimpleRNN(len(vocab))

In [118]:
loss_fn=nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(model.parameters(),lr=learning_rate)

In [119]:
for epoch in range(epochs):
  total_loss=0
  for question,answer in dataloader:

    optimizer.zero_grad()

    # forward pass
    output=model(question)

    # loss
    loss=loss_fn(output,answer[0])

    # backward pass
    loss.backward()

    # update weights
    optimizer.step()

    total_loss+=loss.item()



  print(f"Epoch: {epoch+1}, Loss: {total_loss:4f}")

Epoch: 1, Loss: 524.986515
Epoch: 2, Loss: 455.326884
Epoch: 3, Loss: 373.986092
Epoch: 4, Loss: 314.072499
Epoch: 5, Loss: 262.389605
Epoch: 6, Loss: 214.217127
Epoch: 7, Loss: 170.399265
Epoch: 8, Loss: 132.359189
Epoch: 9, Loss: 101.116281
Epoch: 10, Loss: 76.973283
Epoch: 11, Loss: 59.189895
Epoch: 12, Loss: 46.228507
Epoch: 13, Loss: 36.869093
Epoch: 14, Loss: 30.038010
Epoch: 15, Loss: 25.055459
Epoch: 16, Loss: 21.101635
Epoch: 17, Loss: 17.694688
Epoch: 18, Loss: 15.674923
Epoch: 19, Loss: 13.355947
Epoch: 20, Loss: 11.609188

In [125]:
def predict(model,question,thershold=0.5):

  # Convert Question to Number
  question=text_to_indices(question,vocab)

  # tensor
  question_tensor=torch.tensor(question).unsqueeze(0)

  # send to model
  output=model(question_tensor)

  # convert logits to probs
  probs=torch.nn.functional.softmax(output,dim=1)

  # find index of max probs
  value,index=torch.max(probs,dim=1)


  if value<thershold:
    print("I Don't Know")

  print(list(vocab.keys())[index])

In [127]:
predict(model,"What is the boiling point of water in Celsius?")

100

In [129]:
predict(model,"What is the largest planet in our solar system?")

jupiter

In [130]:
list(vocab.keys())[7]

'paris'